export const SET_PAGINATION_LIMIT = 'SET_PAGINATION_LIMIT'
export const SET_UNREAD_ALERTS_COUNT = 'SET_UNREAD_ALERTS_COUNT'
export const INCREMENT_UNREAD_ALERTS_COUNT = 'INCREMENT_UNREAD_ALERTS_COUNT'
export const DECREMENT_UNREAD_ALERTS_COUNT = 'DECREMENT_UNREAD_ALERTS_COUNT'
