ingress:
  hosts:
    - host: just.staging.woopit.fr
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: bo-front-new-tls
      hosts:
      - just.staging.woopit.fr

extraEnvVars:
  TRANSLATION_URL: "https://storage.googleapis.com/lastmile-prod-i18n-weblate/bo-front-new"
