export const SET_FILTERS = 'SET_FILTERS'
export const SET_ACTIVE_FILTERS = 'SET_ACTIVE_FILTERS'
export const ADD_FILTER = 'ADD_FILTER'
export const REMOVE_FILTER = 'REMOVE_FILTER'

export const SET_IS_PANEL_DISPLAYED = 'SET_IS_PANEL_DISPLAYED'
