import { PackageEntity } from '@/types'

export enum Mode {
  STANDARD = 'standard',
  DELAY = 'delay',
  EXPRESS = 'express',
}

export type Customer = {
  phone: string
  firstName: string
  lastName: string
  email: string
  language: string
  timezone: string
}

export type Collect = {
  id: string
  status: COLLECT_STATUS
  customer: Customer
  start?: string
  end?: string
  mode: Mode
  externalCollectId: string
  externalExchangePlaceId: string
  retailerId: number
  bookingId?: string
  packages: PackageEntity[]
  encryptionMetadata?: string
  exchangePlaceName: string
  createdAt: string
}

export enum COLLECT_STATUS {
  INIT = 'COLLECT_INIT',
  STOCK_OK = 'COLLECT_STOCK_OK',
  STARTED = 'COLLECT_STARTED',
  READY = 'COLLECT_READY',
  AWAITING = 'COLLECT_AWAITING',
  IN_PROGRESS = 'COLLECT_IN_PROGRESS',
  PICK_UP_OK = 'COLLECT_PICK_UP_OK',
  PICK_UP_FAILED = 'COLLECT_PICK_UP_FAILED',
  PICK_UP_PARTIALLY = 'COLLECT_PICK_UP_PARTIALLY',
  REPLANNED = 'COLLECT_REPLANNED',
  CANCELLED = 'COLLECT_CANCELLED',
  DELAYED = 'COLLECT_DELAYED',
  BLOCKED = 'COLLECT_BLOCKED',
}

// current status: list of available status
export const STATUS_WORKFLOW = {
  [COLLECT_STATUS.INIT]: [COLLECT_STATUS.STOCK_OK],
  [COLLECT_STATUS.STOCK_OK]: [COLLECT_STATUS.STARTED],
  [COLLECT_STATUS.STARTED]: [COLLECT_STATUS.READY, COLLECT_STATUS.BLOCKED, COLLECT_STATUS.DELAYED],
  [COLLECT_STATUS.READY]: [COLLECT_STATUS.AWAITING, COLLECT_STATUS.BLOCKED, COLLECT_STATUS.DELAYED],
  [COLLECT_STATUS.AWAITING]: [
    COLLECT_STATUS.IN_PROGRESS,
    COLLECT_STATUS.BLOCKED,
    COLLECT_STATUS.DELAYED,
  ],
  [COLLECT_STATUS.IN_PROGRESS]: [
    COLLECT_STATUS.PICK_UP_OK,
    COLLECT_STATUS.PICK_UP_FAILED,
    COLLECT_STATUS.PICK_UP_PARTIALLY,
    COLLECT_STATUS.BLOCKED,
    COLLECT_STATUS.DELAYED,
  ],
  [COLLECT_STATUS.PICK_UP_PARTIALLY]: [COLLECT_STATUS.BLOCKED, COLLECT_STATUS.DELAYED],
  [COLLECT_STATUS.BLOCKED]: [
    COLLECT_STATUS.INIT,
    COLLECT_STATUS.STOCK_OK,
    COLLECT_STATUS.STARTED,
    COLLECT_STATUS.READY,
    COLLECT_STATUS.AWAITING,
    COLLECT_STATUS.IN_PROGRESS,
    COLLECT_STATUS.PICK_UP_OK,
    COLLECT_STATUS.PICK_UP_FAILED,
    COLLECT_STATUS.PICK_UP_PARTIALLY,
    COLLECT_STATUS.DELAYED,
  ],
  [COLLECT_STATUS.DELAYED]: [
    COLLECT_STATUS.INIT,
    COLLECT_STATUS.STOCK_OK,
    COLLECT_STATUS.STARTED,
    COLLECT_STATUS.READY,
    COLLECT_STATUS.AWAITING,
    COLLECT_STATUS.IN_PROGRESS,
    COLLECT_STATUS.PICK_UP_OK,
    COLLECT_STATUS.PICK_UP_FAILED,
    COLLECT_STATUS.PICK_UP_PARTIALLY,
    COLLECT_STATUS.BLOCKED,
  ],
  [COLLECT_STATUS.REPLANNED]: [COLLECT_STATUS.INIT, COLLECT_STATUS.STOCK_OK, COLLECT_STATUS.READY],
}

export const COLLECT_ERROR_STATUS = [
  COLLECT_STATUS.PICK_UP_FAILED,
  COLLECT_STATUS.PICK_UP_PARTIALLY,
  COLLECT_STATUS.CANCELLED,
]

export type STATUS_WORKFLOW_KEY = keyof typeof STATUS_WORKFLOW
