export const SET_ALL_RULES = 'SET_ALL_RULES'
export const SET_ALL_RULES_GROUPS = 'SET_ALL_RULES_GROUPS'

// Form edit/add rulesGroup
export const RESET_RULES_GROUP = 'RESET_RULES_GROUP'
export const SET_RULES_GROUP = 'SET_RULES_GROUP'
export const SET_RULES_GROUP_NAME = 'SET_RULES_GROUP_NAME'
export const SET_RULES_GROUP_RULES = 'SET_RULES_GROUP_RULES'
export const SET_RULES_GROUP_RULE = 'SET_RULES_GROUP_RULE'
